name: run-tests
on: [push]
jobs: 
  test:
    strategy:
      matrix:
        include:
          - os: windows-latest
            compiler: clang-cl
          - os: windows-latest
            compiler: x86_64-w64-mingw32-gcc
          - os: Ubuntu-latest
            compiler: gcc
          - os: Ubuntu-latest
            compiler: clang
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    steps: 
      - uses: actions/checkout@v4
        with: 
          path: project
      - uses: actions/setup-python@v4
      - uses: FedericoCarboni/setup-ffmpeg@v2
      - uses: jwlawson/actions-setup-cmake@v1.14
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
        if: ${{ matrix.compiler == 'clang-cl' }}
      - uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          static: 0
        if: ${{ matrix.compiler == 'x86_64-w64-mingw32-gcc' }}
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: mkdir build
        working-directory: ./
      - run: cmake ../project -GNinja
        working-directory: ./build
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}
      - run: cmake --build .
        working-directory: ./build
      - run: ctest --output-on-failure
        working-directory: ./build
      - run: cat ./build/Testing/Temporary/LastTest.log
        if: ${{ failure() }}